catalog.row.headers.ID115 <-
  structure(
    list(
      Type =
        c("DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL",
          "DEL", "DEL", "DEL", "DEL", "DEL",
          "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", 
          "DEL", "DEL", "DEL", "DEL", "DEL", 
          "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS",
          "INS", "INS", "INS", "INS", "INS",
          "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS",
          "INS", "INS", "INS", "INS", "INS",
          "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL",
          "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL",
          "DEL", "DEL", "DEL", "DEL", "DEL", "DEL", "INS", "INS", "INS",
          "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS",
          "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS", "INS",
          "INS", "INS", "INS", "DEL", "DEL", "DEL", "DEL", "DEL", "DEL",
          "DEL", "DEL", "DEL", "DEL", "DEL"),
      Subtype =
        c("C", "C", "C", "C", "C", "C", "C", "C", "C",
          "C", "C", "C", "C", "C", 
          "T", "T", "T", "T", "T", "T", "T", "T", "T", 
          "T", "T", "T", "T", "T", 
          "C", "C", "C", "C", "C", "C", "C", "C", "C",
          "C", "C", "C", "C", "C", 
          "T", "T", "T", "T", "T", "T", "T", "T", "T", 
          "T", "T", "T", "T", "T", 
          "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "repeats", "repeats",
          "repeats", "repeats", "repeats", "repeats", "MH", "MH", "MH",
          "MH", "MH", "MH", "MH", "MH", "MH", "MH", "MH"),
      Indel_size =
        c("1", "1", "1", "1", "1", "1", "1", "1", "1", 
          "1", "1", "1", "1", "1", 
          "1", "1", "1", "1", "1", "1", "1", "1", "1", 
          "1", "1", "1", "1", "1", 
          "1", "1", "1", "1", "1", "1", "1", "1", "1", 
          "1","1", "1", "1", "1",
          "1", "1", "1", "1", "1", "1", "1", "1", "1", 
          "1", "1", "1", "1", "1", 
          "2", "2", "2",
          "2", "2", "2", "3", "3", "3", "3", "3", "3", "4", "4", "4", "4",
          "4", "4", "5+", "5+", "5+", "5+", "5+", "5+", "2", "2", "2",
          "2", "2", "2", "3", "3", "3", "3", "3", "3", "4", "4", "4", "4",
          "4", "4", "5+", "5+", "5+", "5+", "5+", "5+", "2", "3", "3",
          "4", "4", "4", "5+", "5+", "5+", "5+", "5+"),
      Repeat_MH_size
      = c("0_AA","0_AT","0_AG","0_TA","0_TT","0_TG","0_GA","0_GT","0_GG",
          "1", "2", "3", "4", "5+", 
          "0_AA","0_AC","0_AG","0_CA","0_CC","0_CG","0_GA","0_GC","0_GG", 
          "1", "2", "3", "4", "5+", 
          "0_AA","0_AT","0_AG","0_TA","0_TT","0_TG","0_GA","0_GT","0_GG",
          "1", "2", "3", "4", "5+", 
          "0_AA","0_AC","0_AG","0_CA","0_CC","0_CG","0_GA","0_GC","0_GG",
          "1", "2", "3", "4", "5+", "0",
          "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0",
          "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0",
          "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "0",
          "1", "2", "3", "4", "5+", "0", "1", "2", "3", "4", "5+", "1",
          "1", "2", "1", "2", "3", "1", "2", "3", "4", "5+")),
    class =
      c("data.table", "data.frame"), row.names = c(NA, -115L)
    #, .internal.selfref = <pointer: 0x0000000008dc1ef0>
  )